// ------------------------------------ ALL ACTION TYPES -----------------------------
// LOGIN ACTIONS
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

// SIGNUP ACTIONS
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// FORGET PASSWORD ACTIONS
export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

// EDIT PROFILE
export const EDIT_PROFILE_LOADING = 'EDIT_PROFILE_LOADING';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// USER ACCOUNT DELETE
export const USER_ACCOUNT_DELETE_LOADING = 'USER_ACCOUNT_DELETE_LOADING';
export const USER_ACCOUNT_DELETE_SUCCESS = 'USER_ACCOUNT_DELETE_SUCCESS';
export const USER_ACCOUNT_DELETE_FAILURE = 'USER_ACCOUNT_DELETE_FAILURE';

// CREATE ACCOUNT MANAGER
export const CREATE_ACCOUNT_MANAGER_LOADING = 'CREATE_ACCOUNT_MANAGER_LOADING';
export const CREATE_ACCOUNT_MANAGER_SUCCESS = 'CREATE_ACCOUNT_MANAGER_SUCCESS';
export const CREATE_ACCOUNT_MANAGER_FAILURE = 'CREATE_ACCOUNT_MANAGER_FAILURE';

// GET ACCOUNT MANAGER DATA
export const GET_ACCOUNT_MANAGER_LOADING = 'GET_ACCOUNT_MANAGER_LOADING';
export const GET_ACCOUNT_MANAGER_SUCCESS = 'GET_ACCOUNT_MANAGER_SUCCESS';
export const GET_ACCOUNT_MANAGER_FAILURE = 'GET_ACCOUNT_MANAGER_FAILURE';

// EDIT ACCOUNT MANAGER DATA
export const EDIT_ACCOUNT_MANAGER_LOADING = 'EDIT_ACCOUNT_MANAGER_LOADING';
export const EDIT_ACCOUNT_MANAGER_SUCCESS = 'EDIT_ACCOUNT_MANAGER_SUCCESS';
export const EDIT_ACCOUNT_MANAGER_FAILURE = 'EDIT_ACCOUNT_MANAGER_FAILURE';

// SEND OTP
export const SEND_OTP_LOADING = 'SEND_OTP_LOADING';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE';

// OTP VERIFICATION
export const OTP_VERIFICATION_LOADING = 'OTP_VERIFICATION_LOADING';
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_FAILURE = 'OTP_VERIFICATION_FAILURE';

//RECOVERING ACCOUNT
export const RECOVER_ACCOUNT_LOADING = 'RECOVER_ACCOUNT_LOADING';
export const RECOVER_ACCOUNT_SUCCESS = 'RECOVER_ACCOUNT_SUCCESS';
export const RECOVER_ACCOUNT_FAILURE = 'RECOVER_ACCOUNT_FAILURE';

//RECOVERING ACCOUNT DATA
export const RECOVER_ACCOUNT_DATA_ADD = 'RECOVER_ACCOUNT_DATA_ADD';
export const RECOVER_ACCOUNT_DATA_REMOVE = 'RECOVER_ACCOUNT_DATA_REMOVE';

// USER_VERIFIED_REQUEST
export const USER_VERIFIED_REQUEST_LOADING = 'USER_VERIFIED_REQUEST_LOADING';
export const USER_VERIFIED_REQUEST_SUCCESS = 'USER_VERIFIED_REQUEST_SUCCESS';
export const USER_VERIFIED_REQUEST_FAILURE = 'USER_VERIFIED_REQUEST_FAILURE';

// ACCOUNT_MANAGER_VERIFIED_REQUEST
export const ACCOUNT_MANAGER_VERIFIED_REQUEST_LOADING =
  'ACCOUNT_MANAGER_VERIFIED_REQUEST_LOADING';
export const ACCOUNT_MANAGER_VERIFIED_REQUEST_SUCCESS =
  'ACCOUNT_MANAGER_VERIFIED_REQUEST_SUCCESS';
export const ACCOUNT_MANAGER_VERIFIED_REQUEST_FAILURE =
  'ACCOUNT_MANAGER_VERIFIED_REQUEST_FAILURE';

// CHANGE PASSWORD USER
export const CHANGE_PASSWORD_USER_LOADING = 'CHANGE_PASSWORD_USER_LOADING';
export const CHANGE_PASSWORD_USER_SUCCESS = 'CHANGE_PASSWORD_USER_SUCCESS';
export const CHANGE_PASSWORD_USER_FAILURE = 'CHANGE_PASSWORD_USER_FAILURE';

// CHANGE EMAIL USER
export const CHANGE_EMAIL_USER_LOADING = 'CHANGE_EMAIL_USER_LOADING';
export const CHANGE_EMAIL_USER_SUCCESS = 'CHANGE_EMAIL_USER_SUCCESS';
export const CHANGE_EMAIL_USER_FAILURE = 'CHANGE_EMAIL_USER_FAILURE';

// GET_USER_PROFILE
export const GET_USER_PROFILE_LOADING = 'GET_USER_PROFILE_LOADING';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

// GET_USER_PROFILE
export const GET_LOGGEDIN_USER_PROFILE_LOADING =
  'GET_LOGGEDIN_USER_PROFILE_LOADING';
export const GET_LOGGEDIN_USER_PROFILE_SUCCESS =
  'GET_LOGGEDIN_USER_PROFILE_SUCCESS';
export const GET_LOGGEDIN_USER_PROFILE_FAILURE =
  'GET_LOGGEDIN_USER_PROFILE_FAILURE';

// GET_ALL_JOBS
export const GET_ALL_JOBS_LOADING = 'GET_ALL_JOBS_LOADING';
export const GET_ALL_JOBS_SUCCESS = 'GET_ALL_JOBS_SUCCESS';
export const GET_ALL_JOBS_FAILURE = 'GET_ALL_JOBS_FAILURE';

// GET QUICK ADS BY ID
export const GET_JOBS_BY_ADS_ID_LOADING = 'GET_JOBS_BY_ADS_ID_LOADING';
export const GET_JOBS_BY_ADS_ID_SUCCESS = 'GET_JOBS_BY_ADS_ID_SUCCESS';
export const GET_JOBS_BY_ADS_ID_FAILURE = 'GET_JOBS_BY_ADS_ID_FAILURE';

// SAVE QUICK ADS
export const SAVE_QUICK_ADS_API_LOADING = 'SAVE_QUICK_ADS_API_LOADING';
export const SAVE_QUICK_ADS_API_SUCCESS = 'SAVE_QUICK_ADS_API_SUCCESS';
export const SAVE_QUICK_ADS_API_FAILURE = 'SAVE_QUICK_ADS_API_FAILURE';

// REMOVE SAVED QUICK ADS
export const REMOVE_SAVED_QUICK_ADS_API_LOADING =
  'REMOVE_SAVED_QUICK_ADS_API_LOADING';
export const REMOVE_SAVED_QUICK_ADS_API_SUCCESS =
  'REMOVE_SAVED_QUICK_ADS_API_SUCCESS';
export const REMOVE_SAVED_QUICK_ADS_API_FAILURE =
  'REMOVE_SAVED_QUICK_ADS_API_FAILURE';

// GET SAVED QUICK ADS
export const GET_SAVED_QUICK_ADS_API_LOADING =
  'GET_SAVED_QUICK_ADS_API_LOADING';
export const GET_SAVED_QUICK_ADS_API_SUCCESS =
  'GET_SAVED_QUICK_ADS_API_SUCCESS';
export const GET_SAVED_QUICK_ADS_API_FAILURE =
  'GET_SAVED_QUICK_ADS_API_FAILURE';

// GET_USER_SERVICE
export const GET_USER_SERVICE_LOADING = 'GET_USER_SERVICE_LOADING';
export const GET_USER_SERVICE_SUCCESS = 'GET_USER_SERVICE_SUCCESS';
export const GET_USER_SERVICE_FAILURE = 'GET_USER_SERVICE_FAILURE';

// CREATE_AND_UPDATE_USER_SERVICE
export const CREATE_AND_UPDATE_USER_SERVICE_LOADING =
  'CREATE_AND_UPDATE_USER_SERVICE_LOADING';
export const CREATE_AND_UPDATE_USER_SERVICE_SUCCESS =
  'CREATE_AND_UPDATE_USER_SERVICE_SUCCESS';
export const CREATE_AND_UPDATE_USER_SERVICE_FAILURE =
  'CREATE_AND_UPDATE_USER_SERVICE_FAILURE';

// DELETE_USER_SERVICE
export const DELETE_USER_SERVICE_LOADING = 'DELETE_USER_SERVICE_LOADING';
export const DELETE_USER_SERVICE_SUCCESS = 'DELETE_USER_SERVICE_SUCCESS';
export const DELETE_USER_SERVICE_FAILURE = 'DELETE_USER_SERVICE_FAILURE';

// CREATE_JOB
export const CREATE_JOB_LOADING = 'CREATE_JOB_LOADING';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

// UPDATE_JOB
export const UPDATE_JOB_LOADING = 'UPDATE_JOB_LOADING';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAILURE = 'UPDATE_JOB_FAILURE';

// DELETE_JOB
export const DELETE_JOB_LOADING = 'DELETE_JOB_LOADING';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAILURE = 'DELETE_JOB_FAILURE';

// GET_ADS.js
export const GET_ADS_LOADING = 'GET_ADS_LOADING';
export const GET_ADS_SUCCESS = 'GET_ADS_SUCCESS';
export const GET_ADS_FAILURE = 'GET_ADS_FAILURE';

// JOB_APPLY
export const JOB_APPLY_LOADING = 'JOB_APPLY_LOADING';
export const JOB_APPLY_SUCCESS = 'JOB_APPLY_SUCCESS';
export const JOB_APPLY_FAILURE = 'JOB_APPLY_FAILURE';

// GET_JOB_BY_DATE_TIME
export const GET_JOB_BY_DATE_TIME_LOADING = 'GET_JOB_BY_DATE_TIME_LOADING';
export const GET_JOB_BY_DATE_TIME_SUCCESS = 'GET_JOB_BY_DATE_TIME_SUCCESS';
export const GET_JOB_BY_DATE_TIME_FAILURE = 'GET_JOB_BY_DATE_TIME_FAILURE';

// UPDATE_APPLICANT_STATUS
export const UPDATE_APPLICANT_STATUS_LOADING =
  'UPDATE_APPLICANT_STATUS_LOADING';
export const UPDATE_APPLICANT_STATUS_SUCCESS =
  'UPDATE_APPLICANT_STATUS_SUCCESS';
export const UPDATE_APPLICANT_STATUS_FAILURE =
  'UPDATE_APPLICANT_STATUS_FAILURE';

// RESET PASSWORD
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';

// CHECK_EXISTING
export const CHECK_EXISTING_LOADING = 'CHECK_EXISTING_LOADING';
export const CHECK_EXISTING_SUCCESS = 'CHECK_EXISTING_SUCCESS';
export const CHECK_EXISTING_FAILURE = 'CHECK_EXISTING_FAILURE';

// SEND_VERIFICATION_EMAIL
export const SEND_VERIFICATION_EMAIL_LOADING =
  'SEND_VERIFICATION_EMAIL_LOADING';
export const SEND_VERIFICATION_EMAIL_SUCCESS =
  'SEND_VERIFICATION_EMAIL_SUCCESS';
export const SEND_VERIFICATION_EMAIL_FAILURE =
  'SEND_VERIFICATION_EMAIL_FAILURE';

// SEND_VERIFICATION_EMAIL
export const EMAIL_VERIFY_STATUS_LOADING = 'EMAIL_VERIFY_STATUS_LOADING';
export const EMAIL_VERIFY_STATUS_SUCCESS = 'EMAIL_VERIFY_STATUS_SUCCESS';
export const EMAIL_VERIFY_STATUS_FAILURE = 'EMAIL_VERIFY_STATUS_FAILURE';

// get country data
export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';

// store profile build data
export const BUILD_PROFILE_DATA = 'BUILD_PROFILE_DATA';
export const BUILD_PROFILE_DATA_REMOVE = 'BUILD_PROFILE_DATA_REMOVE';

export const MOBILE_NUMBER_DATA_SAVE = 'MOBILE_NUMBER_DATA_SAVE';
export const MOBILE_NUMBER_DATA_REMOVE = 'MOBILE_NUMBER_DATA_REMOVE';

// profile buid complete steps
export const COMPLETE_STEPS = 'COMPLETE_STEPS';
export const RESET_STEPS = 'RESET_STEPS'; // New action type

// image upload for S3
export const IMAGE_UPLOAD_LOADING = 'IMAGE_UPLOAD_LOADING';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';

// VIDEO upload for S3
export const VIDEO_UPLOAD_LOADING = 'VIDEO_UPLOAD_LOADING';
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS';
export const VIDEO_UPLOAD_FAILURE = 'VIDEO_UPLOAD_FAILURE';

// image upload for S3
export const AUDIO_UPLOAD_LOADING = 'AUDIO_UPLOAD_LOADING';
export const AUDIO_UPLOAD_SUCCESS = 'AUDIO_UPLOAD_SUCCESS';
export const AUDIO_UPLOAD_FAILURE = 'AUDIO_UPLOAD_FAILURE';

// image upload for S3
export const DOCUMENT_UPLOAD_LOADING = 'DOCUMENT_UPLOAD_LOADING';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAILURE = 'DOCUMENT_UPLOAD_FAILURE';

// MUSIC VIDEO DATA
export const MUSIC_VIDEO_DATA = 'MUSIC_VIDEO_DATA';
// AVAILABLE_QUICKADS
export const AVAILABLE_QUICKADS_LOADING = 'AVAILABLE_QUICKADS_LOADING';
export const AVAILABLE_QUICKADS_SUCCESS = 'AVAILABLE_QUICKADS_SUCCESS';
export const AVAILABLE_QUICKADS_FAILURE = 'AVAILABLE_QUICKADS_FAILURE';

// MY_QUICKADS
export const MY_QUICKADS_LOADING = 'MY_QUICKADS_LOADING';
export const MY_QUICKADS_SUCCESS = 'MY_QUICKADS_SUCCESS';
export const MY_QUICKADS_FAILURE = 'MY_QUICKADS_FAILURE';

// JOB_DETAILS
export const JOB_DETAILS_LOADING = 'JOB_DETAILS_LOADING';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAILURE = 'JOB_DETAILS_FAILURE';

// ACCEPT_JOB
export const ACCEPT_JOB_LOADING = 'ACCEPT_JOB_LOADING';
export const ACCEPT_JOB_SUCCESS = 'ACCEPT_JOB_SUCCESS';
export const ACCEPT_JOB_FAILURE = 'ACCEPT_JOB_FAILURE';

// profile_build api integration
export const PROFILE_BUILD_API_LOADING = 'PROFILE_BUILD_API_LOADING';
export const PROFILE_BUILD_API_SUCCESS = 'PROFILE_BUILD_API_SUCCESS';
export const PROFILE_BUILD_API_FAILURE = 'PROFILE_BUILD_API_FAILURE';

// GET CATEGORY DATA
export const GET_CATEGORY_LOADING = 'GET_CATEGORY_LOADING';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

// GET LANGUAGES DATA
export const GET_LANGUAGES_LOADING = 'GET_LANGUAGES_LOADING';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILURE = 'GET_LANGUAGES_FAILURE';

// GET CHATS DATA JOB
export const GET_CHATS_DATA_SUCCESS = 'GET_CHATS_DATA_SUCCESS';
export const GET_CHATS_DATA_LOADING = 'GET_CHATS_DATA_LOADING';
export const GET_CHATS_DATA_FAILURE = 'GET_CHATS_DATA_FAILURE';

// GET CHATS DATA QUICK
export const QUICK_CHATS_DATA_SUCCESS = 'QUICK_CHATS_DATA_SUCCESS';
export const QUICK_CHATS_DATA_LOADING = 'QUICK_CHATS_DATA_LOADING';
export const QUICK_CHATS_DATA_FAILURE = 'QUICK_CHATS_DATA_FAILURE';

// GET CHATS LIST JOB
export const GET_CHATS_LIST_SUCCESS = 'GET_CHATS_LIST_SUCCESS';
export const GET_CHATS_LIST_LOADING = 'GET_CHATS_LIST_LOADING';
export const GET_CHATS_LIST_FAILURE = 'GET_CHATS_LIST_FAILURE';

// GET CHATS LIST QUICK
export const QUICK_CHATS_LIST_SUCCESS = 'QUICK_CHATS_LIST_SUCCESS';
export const QUICK_CHATS_LIST_LOADING = 'QUICK_CHATS_LIST_LOADING';
export const QUICK_CHATS_LIST_FAILURE = 'QUICK_CHATS_LIST_FAILURE';

// DELETE MESSAGE
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_LOADING = 'DELETE_MESSAGE_LOADING';
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';

// REPORT USER
export const REPORT_USER_LOADING = 'REPORT_USER_LOADING';
export const REPORT_USER_FAILURE = 'REPORT_USER_FAILURE';
export const REPORT_USER_SUCCESS = 'REPORT_USER_SUCCESS';

// REPORT USER
export const REPORT_JOB_LOADING = 'REPORT_JOB_LOADING';
export const REPORT_JOB_FAILURE = 'REPORT_JOB_FAILURE';
export const REPORT_JOB_SUCCESS = 'REPORT_JOB_SUCCESS';

// BLOCK USER
export const BLOCK_USER_LOADING = 'BLOCK_USER_LOADING';
export const BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';

// CREATE JOB STATE PASS
export const DEPOIST_FUNDES_STATE = 'DEPOIST_FUNDES_STATE';
export const DEPOIST_FUNDES_STATE_REMOVE = 'DEPOIST_FUNDES_STATE_REMOVE';

// TWO_FACTOR_AUTH
export const TWO_FACTOR_AUTH_LOADING = 'TWO_FACTOR_AUTH_LOADING';
export const TWO_FACTOR_AUTH_SUCCESS = 'TWO_FACTOR_AUTH_SUCCESS';
export const TWO_FACTOR_AUTH_FAILURE = 'TWO_FACTOR_AUTH_FAILURE';

// CHANGE_DOB
export const CHANGE_DOB_LOADING = 'CHANGE_DOB_LOADING';
export const CHANGE_DOB_FAILURE = 'CHANGE_DOB_FAILURE';
export const CHANGE_DOB_SUCCESS = 'CHANGE_DOB_SUCCESS';

// EDIT_USER_REQUEST
export const EDIT_USER_REQUEST_LOADING = 'EDIT_USER_REQUEST_LOADING';
export const EDIT_USER_REQUEST_FAILURE = 'EDIT_USER_REQUEST_FAILURE';
export const EDIT_USER_REQUEST_SUCCESS = 'EDIT_USER_REQUEST_SUCCESS';

// EDIT_USER_DATA_STORE
export const EDIT_USER_DATA_STORE = 'EDIT_USER_DATA_STORE';
export const EDIT_USER_DATA_REMOVE = 'EDIT_USER_DATA_REMOVE';

// KID_PARENT_CHECK
export const KID_PARENT_CHECK_STORE = 'KID_PARENT_CHECK_STORE';
export const KID_PARENT_CHECK_REMOVE = 'KID_PARENT_CHECK_REMOVE';

// REPLACE ACCOUNT MANAGER
export const REPLACE_ACCOUNT_MANAGER_LOADING =
  'REPLACE_ACCOUNT_MANAGER_LOADING';
export const REPLACE_ACCOUNT_MANAGER_SUCCESS =
  'REPLACE_ACCOUNT_MANAGER_SUCCESS';
export const REPLACE_ACCOUNT_MANAGER_FAILURE =
  'REPLACE_ACCOUNT_MANAGER_FAILURE';

// REPLACE ACCOUNT MANAGER DATA
export const REPLACE_ACCOUNT_MANAGER_DATA_STORE =
  'REPLACE_ACCOUNT_MANAGER_DATA_STORE';
export const REPLACE_ACCOUNT_MANAGER_DATA_REMOVE =
  'REPLACE_ACCOUNT_MANAGER_DATA_REMOVE';

// TO DO LIST ACTION

// ADD TO DO LIST NOTES
export const ADD_TO_DO_LIST_NOTES_LOADING = 'ADD_TO_DO_LIST_NOTES_LOADING';
export const ADD_TO_DO_LIST_NOTES_SUCCESS = 'ADD_TO_DO_LIST_NOTES_SUCCESS';
export const ADD_TO_DO_LIST_NOTES_FAILURE = 'ADD_TO_DO_LIST_NOTES_FAILURE';

// ADD TO DO LIST AUDIO
export const ADD_TO_DO_LIST_AUDIO_LOADING = 'ADD_TO_DO_LIST_AUDIO_LOADING';
export const ADD_TO_DO_LIST_AUDIO_SUCCESS = 'ADD_TO_DO_LIST_AUDIO_SUCCESS';
export const ADD_TO_DO_LIST_AUDIO_FAILURE = 'ADD_TO_DO_LIST_AUDIO_FAILURE';

// ADD VIDEO
export const ADD_TO_DO_LIST_VIDEO_LOADING = 'ADD_TO_DO_LIST_VIDEO_LOADING';
export const ADD_TO_DO_LIST_VIDEO_SUCCESS = 'ADD_TO_DO_LIST_VIDEO_SUCCESS';
export const ADD_TO_DO_LIST_VIDEO_FAILURE = 'ADD_TO_DO_LIST_VIDEO_FAILURE';

// ADD LINK
export const ADD_TO_DO_LIST_LINK_LOADING = 'ADD_TO_DO_LIST_LINK_LOADING';
export const ADD_TO_DO_LIST_LINK_SUCCESS = 'ADD_TO_DO_LIST_LINK_SUCCESS';
export const ADD_TO_DO_LIST_LINK_FAILURE = 'ADD_TO_DO_LIST_LINK_FAILURE';

// ADD PDF
export const ADD_TO_DO_LIST_PDF_LOADING = 'ADD_TO_DO_LIST_PDF_LOADING';
export const ADD_TO_DO_LIST_PDF_SUCCESS = 'ADD_TO_DO_LIST_PDF_SUCCESS';
export const ADD_TO_DO_LIST_PDF_FAILURE = 'ADD_TO_DO_LIST_PDF_FAILURE';

// ADD IMAGE
export const ADD_TO_DO_LIST_IMAGE_LOADING = 'ADD_TO_DO_LIST_IMAGE_LOADING';
export const ADD_TO_DO_LIST_IMAGE_SUCCESS = 'ADD_TO_DO_LIST_IMAGE_SUCCESS';
export const ADD_TO_DO_LIST_IMAGE_FAILURE = 'ADD_TO_DO_LIST_IMAGE_FAILURE';

// ADD SOCIAL MEDIA LINK
export const ADD_SOCIAL_MEDIA_POST_LINK_LOADING =
  'ADD_SOCIAL_MEDIA_POST_LINK_LOADING';
export const ADD_SOCIAL_MEDIA_POST_LINK_SUCCESS =
  'ADD_SOCIAL_MEDIA_POST_LINK_SUCCESS';
export const ADD_SOCIAL_MEDIA_POST_LINK_FAILURE =
  'ADD_SOCIAL_MEDIA_POST_LINK_FAILURE';

// GET_JOBS_BY_APPLICANT_ID_SUCCESS
export const GET_JOBS_BY_APPLICANT_ID_SUCCESS =
  'GET_JOBS_BY_APPLICANT_ID_SUCCESS';
export const GET_JOBS_BY_APPLICANT_ID_LOADING =
  'GET_JOBS_BY_APPLICANT_ID_LOADING';
export const GET_JOBS_BY_APPLICANT_ID_FAILURE =
  'GET_JOBS_BY_APPLICANT_ID_FAILURE';

// USER REVIEW
export const USER_REVIEW_LOADING = 'USER_REVIEW_LOADING';
export const USER_REVIEW_SUCCESS = 'USER_REVIEW_SUCCESS';
export const USER_REVIEW_FAILURE = 'USER_REVIEW_FAILURE';

// USER REVIEW
export const GET_USER_REVIEW_LOADING = 'USER_REVIEW_LOADING';
export const GET_USER_REVIEW_SUCCESS = 'USER_REVIEW_SUCCESS';
export const GET_USER_REVIEW_FAILURE = 'USER_REVIEW_FAILURE';

// USER REVIEW
export const UPDATE_USER_REVIEW_LOADING = 'UPDATE_USER_REVIEW_LOADING';
export const UPDATE_USER_REVIEW_SUCCESS = 'UPDATE_USER_REVIEW_SUCCESS';
export const UPDATE_USER_REVIEW_FAILURE = 'UPDATE_USER_REVIEW_FAILURE';

// USER REVIEW
export const CANCEL_JOB_LOADING = 'CANCEL_JOB_LOADING';
export const CANCEL_JOB_SUCCESS = 'CANCEL_JOB_SUCCESS';
export const CANCEL_JOB_FAILURE = 'CANCEL_JOB_FAILURE';

//FILTER USER
export const SET_FILTER = 'SET_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// QUICK ADS USER CANCEL
export const CANCEL_JOB_QUICKADS_LOADING = 'CANCEL_JOB_QUICKADS_LOADING';
export const CANCEL_JOB_QUICKADS_SUCCESS = 'CANCEL_JOB_QUICKADS_SUCCESS';
export const CANCEL_JOB_QUICKADS_FAILURE = 'CANCEL_JOB_QUICKADS_FAILURE';
