export default {
  done: 'Done',
  bottomTab: {
    NewFax: 'New Fax',
    history: 'History',
    setting: 'Setting',
  },
  button: {
    continue: 'Continue',
    okay: 'Okay',
    submit: 'Submit',
    done: 'Done',
    next: 'Next',
    save: 'Save',
  },
  welcomeScreen: {
    influencers: 'Influencers',
    getStarted: 'Get Started',
    influencersParagraph:
      ' Influence with popular creators from any country in the world. Our creators offer ads, bookings, and much more.',
    chat: 'Chat',
    chatParagraph:
      'No language barriers. Work with global creators by messaging in your language and we’ll automatically translate it into theirs',
    quickAds: 'QuickAds',
    quickAdsParagraph:
      'Advertise to millions of highly engaged followers in minutes.',
    account: 'I already have an account',
    forward: 'Before we move forward',
    influencer18: 'Influencer 18+',
    kids: 'Kids & Under 18',
  },
  signupScreen: {
    getStarted: 'Get Started',
    accountType: 'Select Account Type',
    loremIpsum: 'Lorem Ipsum',
    customerAccount: 'Customer Account',
    accountEx: 'Account explanation details text will be here',
    influencerAccount: 'Influencer Account',
    govermentAccount: 'Goverment Account',
  },
  CredentialsScreen: {
    credentials: 'Credentials',
    subTitle: 'Make sure you have access to your email address.',
    email: 'Email Address',
    confirmEmail: 'Confirm Email Address',
    createPassword: 'Create Password',
    Retype: 'Re-type Password',
    show: 'Show',
    hide: 'Hide',
    govt: 'Provide a government issued email address',
  },
  loginScreen: {
    userName: 'Username or Email',
    password: 'Password',
    forgot: 'Forgot email or password?',
    login: 'Login',
    anyAccount: 'Don’t have any account? Get Started',
  },
  otpScreen: {
    needHelp: 'Need help?',
    please: 'Please email our InfluenceWith support team at',
    wait: 'and wait for a response.',
    verifyAccount: 'Verify your account',
    pleaseConfirm:
      'Please confirm your account by entering the code we’ve sent to',
    resend: 'Resend code',
    resendEmail: 'Resend email',
  },
  forgotCredentialsScreen: {
    forgotCredentials: 'Forgot Credentials',
    please:
      'Please enter your phone number or email address to receive an authentication code.',
    email: 'Email Address',
    phoneNumber: 'Phone Number',
    or: 'Or',
    access: 'I don’t have access to the email or phone number.',
  },
  resetPasswordScreen: {
    resetPassword: 'Reset Password',
    newPassword: 'Enter New Password',
    renterPassword: 'Re-enter New Password',
    show: 'Show',
  },
  thanksScreen: {
    wooo: 'Woohoo, you did it.',
    login: 'Login',
  },
  newProfileDetailsScreen: {
    newProfile: 'New Profile Details',
    letGet: 'Let’s get to know you a little bit more.',
    firstName: 'First Name (listed on ID)',
    lastName: 'Last Name (listed on ID)',
    information:
      'This information is hidden and will not be displayed on your profile. Its only used for verification purposes.',
    createUsername: 'Create a username',
    profileName: 'Profile name (mandatory)',
    characters: '26 characters max.',
    displayed: 'Displayed on your public profile page',
    dateOfBirth: 'Date of Birth',
    pleaseSelectDOB: 'Please select a date of birth',
  },
  managingkidInfluencersScreen: {
    ManagingKid: 'Managing kid influencers',
    accountManagers: 'Account managers must follow guildelines and local laws.',
    purchases:
      'To make purchases on behalf of the kid influencer, the account manager must use their own credit or debit card.',
    agree: 'I agree to follow the guildelines',
    iDontAgree: 'I do not agree',
    local:
      "'Local laws may require you to keep the the kids earning in a separate bank account. it’s your responsbility to check and comply.'",
    app: 'The kid will be the beneficiary of all funds earned through this app.',
    kids: 'We have a zero tolerance policy on indecent exposure of kids.',
  },
  kidsDetailsScreen: {
    kidDetails: 'The Kid’s Details',
    lets: 'Let’s get to know them a little bit more.',
  },
  accountManagerScreen: {
    accountManager: 'Account Manager Details',
    letGet: 'Let’s get to know you a little bit more.',
    firstName: 'First Name (listed on ID)',
    lastName: 'Last Name (listed on ID)',
    dateOfBirth: 'Date of Birth',
    relationship: 'Relationship',
    theParent: 'The parent or legal guardian must be 18+ years of age',
    theInfluencer: 'Age for influencer must be 18+',
    theCustomer: 'Age for customer must be 18+',
    theManager: 'The account manager must be 18+ years of age',
    ifYou:
      'If you’ve made an error please try again. If you are under 18 years of age we cannot allow you to use this platform',
    goBack: 'Go Back',
    quitSetup: 'Quit Setup',
    clicking: 'By clicking continue you agree to the',
    termsConditions: ' terms and conditions',
    youSure: 'Are you sure?',
    cancelSetup:
      ' Are you sure you want to cancel the setup? Your data won’t be saved if you wish to do so.',
    yesSure: 'Yes, I’m Sure',
    occupation: 'Occupation',
    change:
      'You can change account managers at any time from your account settings',
    please: 'Please verify your account',
    replaceManager: 'Replace account manager',
    replaceParent: 'Replace parent/guardian',
    review: 'Verification under review',
    edit: 'Edit profile picture',
    profile: 'Your profile picture may be seen by others',
    email: 'Email address',
    pleaseFill: 'Please fill in this field',
    available: 'This username is available',
  },
  availableSponsorComponent: {
    filter: 'Filter',
    location: 'Location',
    map: 'Map',
  },
  boostProfileComponent: {
    boost: 'BoostProfileComponent',
  },
  myListingsComponent: {
    my: 'MyListingsComponent',
  },
  newProfileKidsTextInput: {
    pleaseSelect: 'Please select a date of birth',
    youMust: 'You must be less than 18 years old',
    thisUsername: 'This username is available',
  },
  badActorScreen: {
    sorry: 'Sorry',
    unfortunately: 'Unfortunately we were unable to verify your request.',
  },
  dontHaveIdScreen: {
    unfortunately: 'Unfortunately, you can’t move forward.',
    platform:
      ' To keep our platform safe and secure, We cannot verify you without a government issued ID.',
    please: 'Please come back once you have this.',
    delete: 'Delete my account',
    goBack: 'Go back! I have an ID',
    sure: 'Are you sure?',
    deleteAccount: 'Are you sure you want to delete your account?',
    iSure: 'Yes, I’m Sure',
    go: 'Go back',
    toKeep:
      'To keep our platform safe and secure, we can only allow you to use InfluenceWith if you agree to our guidelines and terms.',
    age: 'The Business Manager must be 18+ years of age',
  },
  photoVerificationScreen: {
    photo: 'Photo Verification',
    account:
      'The account manager must take a picture and copy the pose displayed.If your pictures match the pose we will verify your profile. Don’t worry nobody will be able to see these pictures besides our verification team.',
  },
  posesMatchScreen: {
    posesMatch: 'Do the poses match?',
    ensure:
      ' Please ensure you try and pose as similar to the demo picture as possible.',
    retake: 'Retake',
    next: 'Next: Final pose',
    submit: 'Submit',
  },
  recoveringAccountScreen: {
    recovering: 'Recovering your account',
    sure: 'To make sure we’re talking to the real you, please answer these questions.',
    purchase: 'What’s the last purchase you made?',
    job: 'What’s the last job you completed?',
    progress: 'Name any jobs that you have in progress',
    access:
      'Enter the phone number & email address that you have lost access to',
    email: 'Email',
    previous: 'Previous',
    next: 'Next',
    talking:
      'To make sure we’re talking to the real you, please answer these questions.',
    fullName: 'What’s your full name?',
    address: 'Address',
    line2: 'Address (line 2)',
    zip: 'ZIP/Postcode',
    submit: 'Submit',
    phoneNumber: 'Phone Number',
    provide: 'Please provide a new way to reach you.',
  },
  rejectDeleteAccountScreen: {
    sorry: 'Sorry',
    create:
      'You will have to create a new account. Your existing account will be closed as per our terms. All active jobs are now cancelled.',
    funds:
      ' All funds in escrow will be held for 28 days and then released to the bank account on file unless stated otherwise.',
    provide:
      'We cannot provide you with access the account data as we could not verify that you are the account holder.',
  },
  rejectRequestScreen: {
    urgent: 'Urgent message from IW',
    received:
      ' We received a request from a person attempting to gain access to your account. Don’t worry, our team has rejected this request and nobody else has access to your account.',
    ensure:
      ' To ensure maximum security, please change your password immediately and enable 2FA',
    login: 'Login and security',
  },
  uploadGovIDScreen: {
    uploadGov: 'Upload Gov. Issued ID',
    please:
      'Please upload the account manager’s Gov issued ID - you may upload an image or simply take a photo of it.',
    id: 'I don’t have an ID.',
    submitGov: 'Submit Gov issued ID',
    reupload: 'Reupload photo ID',
    upload: 'Upload',
    openCamera: 'Open Camera',
    chooseGallery: 'Choose from gallery',
    cancel: 'Cancel',
  },
  yourPartDoneScreen: {
    awesome: 'Awesome, your part is done.',
    review:
      'We’ll review this request and get back to you on the phone number or email that you’ve supplied.',
    reach:
      ' Please reach out to our team at support@influencewith.com if you have any other questions.',
    gotIt: 'Got it',
  },

  settingBottomCards: {
    account: 'Account manager',
    parent: 'Parents/Guardians',
  },

  settingTopProfileCard: {
    managed: 'Managed by parents',
    view: 'View profile',
  },

  governmentOrganizationScreen: {
    government: 'Government Organization',
    following: 'Are you any of the following?',
    local: `Local community projects, local hospital, fire service, police, Millitary, tourism, health and social care, parliament, royalty, olympic commitee`,
    no: 'No, go back',
  },
  newProfileDetailsBusinessScreen: {
    // account: 'Account manager details',
    account: 'New Profile Details',
    little: 'Let’s get to know you a little bit more.',
    company: 'Name of the government organization',
    newCompany: 'What’s the name of the company',
    username: 'Create a username',
    profileName: 'Profile name (mandatory)',
    characters: '26 characters max.',
    displayed: 'Displayed on your public profile page',
    available: 'This username is available',
  },
  phoneNumberScreen: {
    phoneNumber: 'Enter phone number',
    please: 'Please enter your phone number to receive an authentication code.',
    number: 'Phone Number',
    changePhoneNumber: 'Change phone number',
    pleaseEnter: 'Please enter mobile number',
  },
  sentEmailThanksScreen: {
    needHelp: 'Need help?',
    weSent: 'We’ve sent you an email.',
    click:
      'Click the link provided on the email to continue building your profile. The link will expire in 30 minutes.',
    receive: 'Didn’t receive an email? Click to',
    resend: 'resend.',
    helpOptions: 'Help options',
    account:
      'No account has been created yet. If you have entered the wrong email address you can start the sign up process again.',
    alternatively:
      'Alternatively, if you have any other questions please email our InfluenceWith support team at',
    response: 'and wait for a response.',
    startAgain: 'Start again',
    problem: 'Problems with the link?',
    please: 'Please email our InfluenceWith support team at ',
    return: 'Return to settings',
  },
  photoVerificationCameraScreem: {
    loading: 'Loading Camera...',
    copy: 'Copy the pose',
  },
  realAccountHolderScreen: {
    goodNews: 'Good news',
    able: 'We were able to verify you as the account holder.',
    access:
      'To gain access to your account, please reset your credentials now!',
  },
  linkExpiredScreen: {
    linkExpired: 'Link expired',
    security: 'For security reasons you must request another link',
    startAgain: 'Start again',
  },
  buildProfileScreen: {
    now: 'Now, let’s build your profile',
    complete:
      'Complete all of the sign up steps required in order to enter the app.',
    cancel: 'Cancel building my profile',
    setUp: 'Set up your profile picture',
    add: 'Add additional details',
    select: 'Select your tags & categories',
    addMusic: 'Add music & videos',
  },
  jobMessagesComponent: {
    report: 'Report',
    pin: 'Pin',
  },
  aboutProfileCard: {
    online: 'Online Now',
  },
  createNewQuickAdModel: {
    note: 'Note added by the advertiser:',
    asked: 'We asked the advertiser some questions. see their answers below',
    ad: 'Advertiser responded:',
    browse: 'Browse',
    custom: 'Custom usage rights',
    explain: 'Explained by the advertiser:',
  },
  profilePictureScreen: {
    step: 'Step',
    profile: 'Set up your profile picture',
    upload:
      'You can upload an existing photo or take a photo directly within the app.',
    remove: 'Remove',
    add: 'Add profile picture',
    save: 'Save & exit',
    edit: 'Edit profile picture',
  },
  errorComponent: {
    sorry: "Sorry, but you cannot{'\n'} apply to this QuickAd",
    lorem:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui tellus pretium at nisi proing.',
  },
  filterComponent: {
    filter: 'Filter',
    category: 'Category',
    vibe: 'Vibe',
    language: 'Language',
    platform: 'Platform',
    num: 'num_follower',
    show: 'Show_Results',
  },
  addAdditionalDetailsScreen: {
    add: 'Add additional details',
    save: 'Save & exit',
    country: 'Country',
    state: 'State (if they click US)',
    city: 'City',
    gender: 'Gender (optional)',
    why: 'Why do I need to fill this in?',
    select: 'Select all the languages you speak fluently',
    bio: 'Bio',
    what: 'What are you most well-known for?',
    onlyState: 'State',
    selectLanguage: 'Select language',
    selectDialects: 'Select dialect',
    addLanguage: '+ Add another language',
  },
  addIntroVideo2Screen: {
    add: 'Add your intro video',
    edit: 'Edit your intro video',
    success: 'Successfully processed intro video!',
    retake: 'Retake',
    to: 'To record your intro video later, Save & exit',
    you: ' You’re about to submit your intro video',
    review:
      'Review and ensure the video and audio is clear. If you think it needs improvement you can retake it.',
    it: 'It looks good to me',
  },
  addIntroVideoScreen: {
    add: 'Add your intro video',
    edit: 'Edit your intro video',
    able: 'be able to work and collaborate with me.',
    record:
      'Record an intro video using your device camera which appears on your profile page.',
    some: 'Some suggestions of what you can say...',
    guys: 'Hi guys, Welcome to my official ',
    influencer: 'InfluenceWith page. This is where you’ll',
    record: ' To record your intro video later, Save & exit',
    recordVideo: 'Record video',
  },
  addMusicVideosScreen: {
    add: 'Add music & videos',
    have: 'I don’t have music or videos',
    save: 'Save & exit',
    music: '+ Add Your Music',
    video: '+ Add Your Video',
    insertMusic: 'Insert music URL',
    insertVideo: 'Insert video URL',
    import: 'Or import from your device',
    edit: 'Edit video URL',
    deleteVideo: 'Delete video',
    editMusic: 'Edit music URL',
    deleteMusic: 'Delete music',
  },
  selectYourCategoryScreen: {
    select: 'Select your category',
    so: 'So we’ll be able to match profiles accordingly.',
    save: 'Save & exit',
    selectA: 'Select a category',
    digital: 'Digital Products',
    add: 'Add sub-categories (optional)',
    design: 'Design',
    saas: 'Saas',
    tags: 'Select your tags',
  },
  connectSocialAccountsScreen: {
    connect: 'Connect to social accounts',
    showcase:
      'Showcase how many followers you have to users who view your profile.',
    skip: 'Skip for now',
    face: 'Connect to Facebook',
    insta: 'Connect to Instagram',
    you: 'Connect to Youtube',
    twitch: 'Connect to Twitch',
    tiktok: 'Connect to TikTok',
    link: 'Connect to Linkedin',
    snap: 'Connect to Snap',
    twitter: 'Connect to X',
    continue: 'Continue',
  },
  signupSuccessScreen: {
    success: 'Success',
    you: 'You’ve completed your sign-up process.',
  },
  paymentMethodsScreen: {
    paymentMethods: 'Payment methods',
    in: 'In order to make payments, please connect at least one payment account.',
    debitCredit: 'Add debit/credit card',
    bankAccount: 'Add a Bank account',
    paypal: 'Add a PayPal account',
  },
  accountSuspendedScreen: {
    suspended: 'Account suspended',
    account:
      ' This account has been suspended for violating our terms and conditions',
    appeal: 'Appeal suspension',
    request: 'Request my data',
    logout: 'Logout',
  },
  requestDataScreen: {
    request: 'Request your data',
    take: ' We take every effort to ensure we collect very little data about you when you use InfluenceWith.',
    notice:
      ' So you may notice that some things aren’t there, this is because we store as little data as possible of our users while only saving the important things.',
    following: 'The following data will be compiled and provided.',
    information: 'User information',
    jobs: 'Record of jobs',
    record: 'Record of transactions',
    chat: 'Chat logs',
    enter: 'Enter password to request data',
  },
  sorryAboutThisScreen: {
    sorry: 'Sorry about this.',
    something:
      'Something went wrong. Please tell us what you were trying to do and we’ll try to fix it right away.',
    submit: 'Submit feedback',
    cancel: 'Cancel',
    upload: 'Upload screenshots or screen recordings',
  },
  strikeScreen: {
    strike: 'Strike',
    been: 'You have been given a strike because you failed to deliver a job',
    customerName: 'Customer name',
    title: 'This is the title of the QuickAd or job.',
    appeal: 'Appeal this strike',
    continue: 'Continue to the app',
    logout: 'Logout',
  },
  suspendedNextStepScreen: {
    account: 'Account suspended',
    appeal: 'You can appeal this decision if you think we’ve made a mistake',
    sendAppeal: 'Send appeal',
    cancel: 'Cancel appeal',
  },
  thanksLogoutScreen: {
    thanks: 'Thanks',
    review: 'We’ll review your appeal and respond as soon as possible',
    logout: 'Log out',
    request: 'Request my data',
  },
  thanksYourRequestScreen: {
    thanks: 'Thanks for your request!',
    please: 'Please allow us 24 hours to compile and send your data via email.',
    gotIt: 'Got it',
  },
  toContinueScreen: {
    continue: 'To continue',
    follow: 'Follow steps to verify your account',
    uploadID: 'Upload ID',
  },
  viewProfileScreen: {
    report: 'Report this user',
    message: 'Message',
    introVideo: 'Intro Video',
    ageBracket: 'Age bracket',
    bio: 'Bio',
    gender: 'Gender',
    basedIn: 'Based In',
    languages: 'Languages spoken fluently',
    category: 'Category',
    tags: 'Tags',
    myMusic: 'My Music',
    seeAll: 'See all',
    myVideos: 'My Videos',
    actingShowreel: 'Acting Showreel',
    musicVideo: 'Music Video',
    reviews: 'Reviews',
  },
  settingScreen: {
    editProfile: 'Edit Profile',
    referrals: 'Referrals',
    payments: 'Payments',
    analytics: 'Analytics',
    manageServices: 'Manage my services',
    loginSecurity: 'Login and security',
    socialAccounts: 'Connected social accounts',
    language: 'Language',
    logout: 'Log out',
    help: 'Help & FAQ',
  },
  // accountManagerScreen: {
  //   edit: 'Edit profile picture',
  //   profile: 'Your profile picture may be seen by others',
  //   please: 'Please verify your account',
  // },
  twoStepVerificationScreen: {
    verifications: '2 verifications needed',
    complete:
      '2 verifications needed Complete all of the verification steps required in order to unlock all of the app features.',
    parent: 'Verify the Parent/Guardian',
    little: 'Verify Little Timmy',
  },
  accountDeletedThanksScreen: {
    account: 'Account has been deleted.',
    please: 'Please allow us 24 hours to compile and send your data via email.',
  },
  actingServicesSettingsScreen: {
    acting: 'Acting services settings',
    allow:
      'Allow customers to send you offers to cast you in shows, movies and more.',
    casting: 'Casting in a production',
    products:
      ' Allow customers to send you offers to advertise their products and services',
    only: 'Only allow offers in excess of',
    save: 'Save',
    customers:
      'Customers will see this. They will not be able to send you offers if its lower than this amount.',
    proposals: 'You will receive proposals',
    special: 'Special requirements',
    requirements:
      'Your special requirements will be displayed to customers who wish to book you in person. They can then confirm whether they can accommodate for your requirements.',
    dietary: 'Dietary requirements',
    send: 'Allow customers to send you offers to advertise their products and services',
    EnterTitle: 'Enter the title',
    describeMore: 'Describe more',
    dietaryRequirements: 'Dietary requirements',
    peanuts:
      'I cannot be in the same room as peanuts. Type here to let customers know what they must do to accommodate for this, if they want to book you in person',
    delete: 'Delete',
    edit: 'Edit',
    addAnother: 'Add Another',
    manage: ' You can change these at any time via manage services',
  },
  addBankAccountScreen: {
    addBack: 'Add bank account',
    fullName: 'Full Name',
    sortCode: 'Sort code',
    accountNumber: 'Account Number',
    confirmAccount: 'Confirm Account Number',
    routingNumber: 'Routing Number',
  },
  addDebitCreditCardScreen: {
    addDebitCard: 'Add debit/credit card',
    cardNumber: 'Card number',
    scanCard: 'Scan card',
    cardholderName: 'Cardholder name',
    expirationDate: 'Expiration date',
    cvv: 'CVV',
    setDefault: 'Set as default',
    billingAddress: 'Billing address',
    address: 'Address',
    addressLine: 'Address (line 2)',
    city: 'City',
    country: 'Country',
    zip: 'Zip/Postcode',
  },
  advertisementSettingsScreen: {
    advertisementSettings: 'Advertisement settings',
    customers:
      'Allow customers to send you offers to advertise their products and services',
    youtube: 'Youtube',
    allow:
      'Allow customers to send you offers to advertise their products and services',
    only: 'Only allow offers in excess of',
    services: 'Services you offer in this platform',
    customersWill:
      'Customers will see this. They will not be able to send you offers if its lower than this amount.',
    video: 'Video',
    liveStream: 'Live stream',
    story: 'Story',
    youWill: 'You will receive proposals',
  },
  analyticsScreen: {
    analytics: 'Analytics',
    previous: `< Previous week`,
    next: `Next week >`,
    total: 'Total value of outgoing proposals',
    boost: 'Boost again 🚀',
    influenceWith: 'InfluenceWith',
    discovered:
      'You were discovered mostly in multiple locations and categories',
    dataAnalytics: 'Data Analytics',
    profileViews: ' Profile Views',
    bookings: 'Bookings',
    advertisements: 'Advertisements',
    musicServices: 'Music services',
    actingServices: 'Acting services',
    totalValue: 'Total value',
    proposalsReceived: 'Proposals received',
    returnInvestment: 'Return on investment',
    success: 'Success!',
    goodLuck:
      'Good luck with your upcoming projects & we hope to see you boost your profile again soon',
  },
  blogScreen: {
    blog: 'Blog',
    readMore: 'Read more',
  },
  blogTitleScreen: {
    blogTitle: 'Blog title',
    there:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
    all: 'All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
  },
  bookingSettingsScreen: {
    bookingSettings: 'Booking settings',
    allow:
      'Allow customers to send you offers to book you for commercial work, appearances and special occasions.',
    casting: 'Casting in a production',
    customers:
      'Allow customers to send you offers to advertise their products and services',
    only: 'Only allow offers in excess of',
    customersWill:
      'Customers will see this. They will not be able to send you offers if its lower than this amount.',
    youWill: 'You will receive proposals',
    specialRequirements: 'Special requirements',
    special:
      ' Your special requirements will be displayed to customers who wish to book you in person. They can then confirm whether they can accommodate for your requirements.',
    dietary: 'Dietary requirements',
    allowCustomers:
      'Allow customers to send you offers to advertise their products and services',
    enter: 'Enter the title',
    describeMore: 'Describe more',
    dietaryRequirements: 'Dietary requirements',
    veganLifestyle: 'Vegan lifestyle',
    cannot:
      ' I cannot be in the same room as peanuts. Type here to let customers know what they must do to accommodate for this, if they want to book you in person',
    delete: 'Delete',
    edit: 'Edit',
    addAnother: 'Add Another',
    change: 'You can change these at any time via manage services',
  },
  cantDeleteAccountScreen: {
    account: 'Account has been deleted.',
    weCant: 'We can’t delete your account.',
    youCannot:
      'You cannot delete your account Until the following are completed',
    unfinishedJobs: '1. Unfinished Jobs',
    withdraw: ' 2. Withdraw the remaining available balance in your account',
    return: 'Return to settings',
  },
  changeDOBScreen: {
    changeDOB: 'Change date of birth',
    currentDOB: 'Current DOB',
    enterDOB: 'Enter DOB',
    selectReason: 'Select a reason',
    pleaseFill: 'Please fill all fields',
  },
  changeEmailAddressScreen: {
    changeEmail: 'Change email address',
    currentEmail: 'Current email address',
    newEmail: 'New email address',
    confirmEmail: 'Confirm new email address',
  },
  changePasswordScreen: {
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'Enter New Password',
    show: 'Show',
    reEnter: 'Re-enter New Password',
    hide: 'Hide',
  },
  verifyLittleTimmyScreen: {
    last: 'Lastly, verify Little Timmy',
    lorem:
      'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to',
  },
  deleteMyAccountScreen: {
    deleteAccount: 'Delete my account',
    whyDo: 'Why do you want to delete your account?',
    selectReason: 'Select a reason',
    chat: 'Chat with our support team',
    please: 'Please give a reason',
  },
  deleteMyAccountSecScreen: {
    deleteAccount: 'Delete my account',
    whyDo: 'Why do you want to delete your account?',
    enterPassword: 'Enter Password',
    importantNotice: 'Important Notice',
    youWill: 'You will lose all of your account data',
    chatHistory: 'Chat History',
    jobHistory: 'Job History',
    allImage:
      ' All images, videos, audio will be deleted Including media connected to jobs',
    create:
      'You will need to create a new account If you wish to sign up again and go through the verification steps again.',
    understand:
      'I understand and agree to the account deletion Terms and liability clause.',
    iWould: 'I would like to request my data',
  },
  describeIssueScreen: {
    describeIssue: 'Describe the issue',
    select: 'Select the closest match',
  },
  editProfileScreen: {
    introVideo: 'Intro Video',
    firstName: 'First Name (listed on ID)',
    lastName: 'Last Name (listed on ID)',
    companyName: 'Company name',
    govtOrganization: 'Govt. organization name',
    username: 'Username',
    profileName: 'Profile name',
    bio: 'Bio',
    gender: 'Gender (optional)',
    basedIn: 'Based in',
    state: 'State',
    city: 'City',
    languagesFluently: 'Languages spoken fluently',
    requestChange: 'Request to change',
    category: 'Category',
    subCategory: 'Subcategory',
    tags: 'Tags',
  },
  faqScreen: {
    faq: 'FAQ',
    how: 'How are the numbers calculated?',
    much: 'How much do i earn?',
  },
  helpCenterScreen: {
    helpCenter: 'Help Center',
    tips: 'Tips for QuickAds',
    featured: 'Featured blog post',
    blog: 'Blog',
    faq: 'FAQs',
    internationalLaws: 'International Laws',
    chat: 'Chat with IW support team',
  },
  howDoSigninScreen: {
    howDo: 'How do i sign in',
    information: 'Was this information useful?',
    yes: 'Yes',
    no: 'No',
    return: 'Return to help center',
    talk: 'Talk to support team',
  },
  incomeHistoryScreen: {
    incomeHistory: 'Income History',
    filter: 'Filter',
    details: 'Details',
    title: 'Title',
    advertise: ' Advertise the new apple wa..',
    serviceType: 'Service type',
    customersName: 'Customers name',
    totalEarned: 'Total earned',
    iWCommission: 'IW commission',
    stripeFee: 'Stripe fee',
    paidYou: 'Paid to you',
    status: 'Status',
    dateCompleted: 'Date completed',
    exportPDF: 'Export as PDF',
    iNeedHelp: 'I need help',
    viewJob: 'View job',
    filterWithdrawals: 'Filter Withdrawals',
    filterIncome: 'Filter income',
    resetFilters: 'Reset Filters',
    period: 'Period',
    incometype: 'Income type',
    apply: 'Apply',
    ExportAllPDF: 'Export all as PDF',
    ExportAllCSV: 'Export all as CSV',
    ChatSupport: 'Chat with support team',
  },
  internationalLawsScreen: {
    IntLaws: `Int’l laws`,
    bookmarkedTopics: 'Bookmarked topics',
    advertising: 'UK advertising standards',
    influencerGuidelines: 'Influencer guidelines',
    australianNews: 'Australian News',
    lorem: 'Lorem ipsum dolor sit amet',
    denmark: 'Denmark',
  },
  loginSecurityScreen: {
    loginSecurity: 'Login & Security',
    change: 'Change email address',
    changePassword: 'Change password',
    changePhoneNumber: 'Change phone number',
    authentication: '2-factor authentication',
    yourDOB: 'Your date of birth',
    requestData: 'Request your data',
    deleteAccount: 'Delete my account',
    timmy: 'Little Timmy’s Date of Birth',
  },
  makePaymentsScreen: {
    makePayment: 'To make payments',
    addPayment: 'Add new payment method',
    setDefault: 'Set as default',
    edit: 'Edit',
    delete: 'Delete',
    areSure: 'Are you sure you want to remove payment method?',
    lorem: 'Lorem ipsum such as any pending payments will still go through',
    noGoBack: 'No, Go Back',
    remove: 'Remove',
  },
  manageMusicScreen: {
    manageMusic: 'Manage Music',
    music: 'Music: Justin Bieber - Holy',
  },
  manageVideoScreen: {
    manageVideos: 'Manage Videos',
  },
  manageYourServicesScreen: {
    needHelp: 'Need help?',
    manageServices: 'Manage your services',
    click:
      'Click on a service to modify offerings, set your rates, or turn the service on/off',
    advertisements: 'Advertisements',
    actingServices: 'Acting services',
    bookings: 'Bookings',
    licensingDeals: 'Licensing deals',
    musicServices: 'Music services',
    specialRequirements: 'My special requirements',
    letCustomers:
      'Let customers know your special requirements in advance. You can add/edit requirements from here such as allergy notices, accessibility or any other special requirements.',
    postalAddress: 'My postal Address',
    remove: 'Add/edit or remove your PO Box address.',
    on: 'ON',
    off: 'OFF',
  },
  phoneNumberConfirmedScreen: {
    return: 'Return to login & security',
    confirmed: 'Phone number confirmed!',
    thanks: 'Thanks for keeping your account up to date!',
  },
  mySpecialRequirementsScreen: {
    special: 'My special requirements',
    requirements:
      'Your special requirements will be displayed to customers who wish to book you in person. They can then confirm whether they can accommodate for your requirements.',
    display: 'Display my special requirements for',
    acting: 'Acting services',
    bookings: 'Bookings',
    dietaryRequirements: 'Dietary requirements',
    customers:
      ' Allow customers to send you offers to advertise their products and services',
    title: 'Enter the title',
    describeMore: 'Describe more',
    veganLifestyle: 'Vegan lifestyle',
    cannot:
      ' I cannot be in the same room as peanuts. Type here to let customers know what they must do to accommodate for this, if they want to book you in person',
    delete: 'Delete',
    edit: 'Edit',
    addAnother: 'Add Another',
    change: ' You can change these at any time via manage services',
  },
  passwordChangedThanksScreen: {
    passwordChanged: 'Password Changed',
    return: 'Return to login & security',
  },
  paymentsScreen: {
    payments: 'Payments',
    pending: 'pending',
    incomeHistory: 'Income history',
    viewAll: 'View all',
    spendingHistory: 'Spending history',
    paymentMethods: 'Payment methods',
    makePayments: 'To make payments',
    addPaymentMethod: 'Add a payment method',
    default: 'Default',
    withdrawalMethods: 'Withdrawal methods',
    receivePayouts: 'To receive payouts',
    addwithdrawalMethod: 'Add a withdrawal method',
    taxForms: 'Tax Forms',
    viewDetails: 'View Details',
    currency: 'Currency',
    withdraw: 'Withdraw',
    withdrawalHistory: 'Withdrawal history',
  },
  paymentSuccessScreen: {
    success: 'Success!',
    lorem:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui tellus pretium at nisi proin. Semper elementum gravida sem sed facilisi. Aenean sit elementum amet eget velit neque adipiscing.',
    backPayments: 'Back to payments',
  },
  postalAddressScreen: {
    postalAddress: 'Postal Address',
    iNeed: 'Why do I need a postal address?',
    customers:
      'Customers may want to send you items to try out and promote on social media',
    toSafe:
      'To be safe we recommend that you use a postal box address instead of your actual home address',
    ifPostal:
      'If you do not have a postal service, don’t worry you can skip for now by switching the visibility to OFF and set this up later at any time',
    addressOne: 'Address Line 1',
    addressTwo: 'Address Line 2',
    city: 'City',
    state: 'State',
    postCode: 'Post code/Zip code',
    country: 'Country',
    control: 'Control who can see your postal address',
    customersWho: 'Customers who send me job proposals for',
    actingServices: 'Acting services',
  },
  referralsListScreen: {
    referrals: 'Referrals',
    active: 'Active',
    expired: 'Expired',
    viewProfile: 'View profile',
    iNeedHelp: 'I need help',
    viewFAQs: 'View FAQs',
    chatWith: 'Chat with support',
  },
  referralsScreen: {
    referrals: 'Referrals',
    youUnique: 'Your unique code',
    earnings: 'Earnings',
    already: 'We’ve already added this to your available balance',
    totalEarnings: 'Total earnings',
    inThePost: 'In the past 7 days',
    viewAll: 'View all referrals',
    faqs: 'FAQs',
    howOften: 'How often will I get paid?',
    howMuch: 'How much do i earn?',
    youReceive:
      'You receive 5% of the earnings of every single person who signs up to Influence With using your unique referral code and makes money on the platform. T&C’s apply.',
  },
  requestDataThanksScreen: {
    thanks: 'Thanks for your request!',
    please:
      ' Please allow us 24 hours to compile and send your data via email.',
    gotIt: 'Got it',
  },
  editProfileThanksScreen: {
    thanks: 'Thanks',
    aim: 'We aim to review all verifications requests within 24 hours.',
    aimMean:
      'This could take 24 hours. In the meantime, some app features will be unavailable until we verify you.',
    back: 'Back to settings',
    review: 'We’re reviewing your request.',
    got: 'Got it',
    managerReplace: 'This could take 24 hours.',
  },
  requestYourDataScreen: {
    requestData: 'Request your data',
    weTake:
      ' We take every effort to ensure we collect very little data about you when you use InfluenceWith.',
    soYou:
      ' So you may notice that some things aren’t there, this is because we store as little data as possible of our users while only saving the important things.',
    following: ' The following data will be compiled and provided.',
    userInformation: 'User information',
    recordJobs: 'Record of jobs',
    record: 'Record of transactions',
    chatLogs: 'Chat logs',
    enterPass: 'Enter password to request data',
  },
  savedTopicsDetailScreen: {
    uk: 'UK advertising standards',
    lorem:
      ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Risus aliquam dolor scelerisque mauris natoque dui. Ipsum a eget aliquam eget ac eget diam. Tempor, senectus facilisis id odio scelerisque convallis eros. Tellus lectus lacus, ultrices viverra. Varius tempor posuere orci fermentum sit consequat eu laoreet. Pharetra rhoncus ante praesent turpis et. Eget aliquam auctor feugiat libero tempor enim habitasse. Aliquet tristique sem ut porttitor consequat diam sed sodales tortor. Amet tincidunt vel facilisi tellus pharetra, amet, nibh magna. Cursus bibendum habitant nulla viverra consectetur. Consequat, donec auctor eget enim. Sodales tempus facilisi adipiscing magna suspendisse sed. Viverra id aliquam venenatis in massa ultrices. Proin suspendisse nunc, nibh tincidunt netus pharetra. Leo eget augue massa mattis in mi lacus. Cursus arcu elit malesuada senectus laoreet mi. Nunc maecenas nec lorem praesent. Lorem egestas neque porttitor quam duis et. Commodo at pulvinar sapien mi scelerisque semper sit. Proin a, ante odio sed morbi id facilisis tortor enim. Vitae malesuada feugiat vitae lectus.',
    follow: 'Follow for updates',
  },
  savedTopicsScreen: {
    savedTopics: 'Saved topics',
    lorem:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam adipiscingtea lorem.',
    readMore: 'Read more',
  },
  selectLanguageScreen: {
    // selectLanguage: 'Select Language',
    selectLanguage: 'Select your language',
  },
  spendingHistoryScreen: {
    spendingHistory: 'Spending History',
    filter: 'Filter',
  },
  supportInboxScreen: {
    supportInbox: 'Support inbox',
    openCases: 'Open cases',
    closedCases: 'Closed cases',
    startNewChat: 'Start a new chat',
  },
  taxResponsibilityScreen: {
    taxResponsibility: 'Tax responsibility',
    cta: 'CTA',
  },
  tipsQuickAdsScreen: {
    tipsQuickAds: 'Tips for QuickAds',
  },
  twoFactorAuthenticationScreen: {
    twoFactor: 'Two-factor Authentication',
    toProtect:
      'To protect your account, we’ll send you a security code every time you attempt to log in.',
    email: 'Email Authentication Code',
  },
  withdrawalHistoryScreen: {
    withdrawal: 'Withdrawal History',
    filter: 'Filter',
    details: 'Details',
    withdrawalf: 'withdrawal',
    withdrawalType: 'Withdrawal type',
    stripeFee: 'Stripe fee',
    paidYou: 'Paid to you',
    status: 'Status',
    transactionDate: 'Transaction date',
    exportPDF: 'Export as PDF',
    iNeedHelp: 'I need help',
    viewFAQs: 'View FAQs',
    chatSupport: 'Chat with support',
    filterWithdrawals: 'Filter Withdrawals',
    resetFilters: 'Reset Filters',
    period: 'Period',
    apply: 'Apply',
  },
  withdrawBalanceScreen: {
    withdrawBalance: 'Withdraw balance',
    transferTo: 'Transfer to',
    stripeFee: 'Stripe fee',
    youWillReceive: 'You will receive',
    shouldArrive: 'Should arrive in',
    enterAmount: 'Enter amount',
    addNew: 'Add New',
  },
  withdrawFundsScreen: {
    withdrawFunds: 'Withdraw funds',
    inOrder:
      'In order to receive payments, please connect at least one payment account.',
    addBankAccount: 'Add a bank account',
    addPayPalAccount: 'Add a PayPal account',
    connectPayoneer: 'Connect to Payoneer',
    addDebitCreditCard: 'Add debit card',
  },
  logoutPopup: {
    doYou: 'Do you want to log out?',
    areYou: 'Are you sure you want to log out?',
    no: 'No',
    yes: 'Yes',
  },
  overRideConflictsPopup: {
    please: 'Please confirm that you are able to accept this job.',
    failure: 'Failure to deliver job can lead to strikes.',
    overRideBurnOut: 'Override the burnout threshold',
    able: 'I am able to deliver this job',
    overRideConflicts: 'Override the date and time conflict',
    strikes: '3 strikes lead to account suspension.',
    accept: 'Accept Job',
    skip: 'Skip Job',
  },
  licensingDealSettingsScreen: {
    licensing: 'Licensing deal settings',
    allow:
      'Allow customers to send you offers to licence your name, image, brand or likeliness on their products and services.',
    product: 'Product and Services',
    only: 'Only allow offers in excess of',
  },
  musicServicesSettingsScreen: {
    music: 'Music services settings',
    allow:
      'Allow customers to send you offers to licence your name, image, brand or likeliness on their products and services.',
    musicFeatures: 'Music Features',
    only: 'Only allow offers in excess of',
  },
  // {mahander sir }
  quickAdsHomescreen: {
    save: 'Save',
    unsave: 'Unsave',
    remove: 'Remove',
    QuickAds: 'QuickAds',
    Available: 'Available',
    MyQuickAds: 'My QuickAds',
    gallery: 'Browse gallery',
    Filter: 'Filter',
    Location: 'Location',
    search: 'Search',
    NoQuickAds: 'No QuickAds',
    PostQuickAds: 'Post QuickAds',
    Spaces_remaining: 'Spaces remaining',
    daysLeft: 'Day(s) left to accept',
    Language: 'Language',
    Platform: 'Platform',
    Followers: 'Followers',
    Target: 'Target',
    earning: 'You earn',
    published: 'Published',
    Save: 'Save',
    unSave: 'Unsave',
    View: 'View',
    Reset: 'Reset',
    Category: 'Category',
    Vibe: 'Vibe',
    num_follower: 'Number of Followers',
    Show_Results: 'Show Results',
    country: 'Country',
    state: 'State',
    city: 'City',
    saved: 'Saved',
    next: 'Next',
    saved_long: 'QuickAds that have expired will be removed from here.',
    nothing_save: 'Nothing Saved',
    Recommended: 'Recommended for you',
    noResult: 'No results found',
    create_new: 'Create New QuickAd',
    showing: 'Showing',
    pay_offer: 'Pay offered',
    update: 'Updates',
    payDeposit: 'Pay deposit',
    processing: 'In progress',
    Completed: 'Completed',
    A_new_QuickAds: 'Create a new QuickAd',
    A_new_QuickAds1:
      'Advertise to millions of highly engaged followers in minutes*',
    message: 'Message',
    online_now: 'Online Now',
    quick_title: 'QuickAd Title',
    add_Image: 'Add a thumbnail image',
    Browse_gallery: 'Browse gallery',
    Browse_files: 'Browse files',
    Browse_images: 'Browse Images',
    Browse_videos: 'Browse Videos',
    Cancel: 'Cancel',
    select_Category: 'Select Category',
    set_age: 'Set an age limit for applicants',
    age_limit: 'Age Limit',
    all_age: 'All Ages',
    child_age: 'Child influencers managed by guardians',
    age_18: 'Over 18 years old',
    age_21: 'Over 21 years old',
    age_25: 'Over 25 years old',
    Suggested: 'Suggested',
    The_QuickAd: 'The QuickAd',
    Short_brief: 'Short brief about the QuickAd',
    Write_here: 'Write here',
    Website_link: 'Website link',
    Media_Files: 'Media or Files',
    Disclosure_notices: 'Disclosure notices',
    select: 'Select',
    Content_usage: 'Content usage rights',
    influencers_promote: 'How many influencers should promote your QuickAd?',
    minimum_influencers:
      'Minimum number of followers each influencer should have',
    The_platform: 'The platform',
    follower_number:
      'Minimum number of followers each influencer should have on this platform',
    enter_number: 'Enter a number',
    minimum: 'Minimum',
    Date_time: 'Date and time',
    When_to_post: 'When to post',
    Select_Date: 'Select Date',
    Select_time: 'Select Time',
    the_vibe: 'The vibe',
    Target_audience: 'Target audience',
    payment: 'Payment',
    which_languange: 'Which language should this be spoken in',
    set_mood: 'Set a mood for this QuickAd',
    set_mood1: 'Set the mood for this Ad',
    Swearing: 'Swearing',
    Swearing_language: 'Swearing or foul language',
    Select_country: 'Select country',
    Select_state: 'Select state',
    Select_city: 'Select city',
    Select_age_bracket: 'Select age bracket',
    Selected_age_bracket: 'Selected age bracket',
    target_coutry: 'Target Countries',
    target_state: 'Target States',
    target_city: 'Target Cities',
    target_age: 'Age Range',
    Payment_offered: 'Payment offered',
    Select_currency: 'Select your currency',
    currency_dec:
      'This is the currency you will be billed in.\nThis is also the currency that your influencers will be paid.',
    Per_Influencer: 'Per Influencer',
    complete_all: 'complete all of the fields above to continue',
    titleText: 'Job proposal contains the following',
    Questions: 'Questions',
    further: 'Add a note to explain further',
    Review: 'Review',
    Political: 'Political Advertisement',
    NoteAdded: 'Note added by the Advertiser',
    continue: 'Continue',
    add_note: `Tap + to add a note`,
    only_you: 'Only you can see this information',
    summary: 'Summary',
    total_price: 'Total price you’ll pay',
    taxes: 'Taxes',
    limitReached: 'Limit reached',
    social_license: 'Social media license',
    content_usage: 'Custom usage rights',
    receipt: 'Receipt',
    service: 'Service: QuickAds',
    serviceDec:
      'Advertise the new apple watch series 6 which is available on cellular plants',
    influencer: 'Influencer',
    paymentEscrow: 'Payment in escrow',
    TotalSpent: 'Total spent',
    needHelp: 'Need help?',
    contactSupport: 'Contact support',
    my_schedule: 'See my schedule',
    report_proposal: 'Report this proposal',
    accept_Job: 'Accept Job',
    skip_Job: 'Skip Job',
    waiting: 'Waiting for applicants...',
    waiting_Dec:
      'If influencers cancel before delivering, we automatically place the listing with the remaining spot back on QuickAds for more influencers to apply and fill in the gap',
    Status: 'Status',
    Escrow_Doc: 'We’ll notify you when influencers apply.',
    more: 'More...',
  },
  editProfileImageCard: {
    managed: 'Managed by parents',
  },
  toDoAllMediaScreen: {
    uplaod: 'Upload Images',
    images: 'Uploaded Images',
    uploadVIdeo: 'Upload Videos',
    video: 'Uploaded Videos',
    uploadAudio: 'Upload Audio',
    links: 'Uploaded Links',
    audio: 'Uploaded Audio',
    title: 'Title',
    link: 'Enter Link',
    add: 'Add',
    document: 'Upload Docs',
    enterUrl: 'Enter the URL for a social media post',
    manage: 'Manage Social Posts',
    all: 'All Files',
    media: 'Media & Files',
    downloadImages: 'Download all images',
    downloadDocuments: 'Download all documents',
    downloadAudios: 'Download all audio',
    downloadVideos: 'Download all videos',
    downloadLinks: 'Download all links',
    singleImages: 'Images',
    singleVideos: 'Videos',
    singleAudios: 'Audio',
    singleLinks: 'Links',
    singleDocs: 'Docs',
    social: 'Social posts analytics',
  },

  MessageingScreen: {
    search: 'Search',
    save: 'Save',
    report: 'Report',
    Job_Messages: 'Job Messages',
    Quick_Chats: 'Quick Chats',
    no_Job_message: 'There are no messages!',
    job_message:
      'You can search users to message or visit a users profile page and click the message button',
    Translation_Settings: 'Translation Settings',
    Translation_Assistant: 'Translation Assistant',
    Translation_All: 'Translate all messages to this language',
    tell_us: 'Tell us why you are reporting this user',
    Send_report: 'Send report',
    Block_Username: 'Block Username',
    return_messages: 'Return to messages',
    browse: 'Browse',
    on_off: 'Change or turn off',
    Chat_search: 'Chat search',
    search_keyword: 'Search for key words within this chat',
    all_media: 'View all media files within this chat',
    download_media: 'View and download all media files in this chat',
    export_file: 'Export the text in this chat as a PDF file',
    export_dec: 'This does not include any media files or attachments',
    block_user: 'Report & block user',
    block_dec: 'Report and block this user',
    images: 'Images',
    video: 'Video',
    audio: 'Audio',
    links: 'Links',
    docs: 'Docs',
    save_page: 'Save to pages',
    save_file: 'Save to files',
    cancel: 'Cancel',
    send_content: 'Send content for approval',
    upload_file: 'Upload files',
    upload_photo: 'Upload photos or videos',
    upload_camera: 'Take photo or video',
    Browse_camera: 'Browse camera roll',
    Browse_files: 'Browse files',
    before_you: 'Before you continue',
    camera_warning: `Risk warning ⚠️
This is a business message. 
    
Do not send “test photos or videos” of yourself using your device camera endorsing or promoting a product or service. 
    
You may be tricked into promoting a business unknowingly and without compensation.
We cannot help you if a brand begins using any photos and videos you have taken, as promotional content elsewhere and you may not get paid at all. 

Keep photos and videos you send via messages generic and non promotional.
    
How to stay safe and get paid 
To use our message feature safely and ensure that you get paid, you should only send content for approval via messages once you have entered into a job with a user and you have been notified by InfluenceWith that the customer has deposited the funds into escrow.`,
  },
};
